### ISSUE TITLE
Use .babelrc configuration if file exists

### ISSUE THREAD

**Issue by bokub** [bokub/lyo#2]
When running `lyo` (not `lyo get`), it would be great to check if a `.babelrc` file exists, and override the default babel configuration if true.

**Comment by thakkaryash94** [comment]
I would like to work on this issue. From what I understand, I think need to change [runcBabel](https://github.com/bokub/lyo/blob/master/lib/task.js#L41) function in task.js at line 42. Am I in the right direction?

**Comment by bokub** [comment]
Yeah,

At first you would need to check if a `.babelrc` file exists in [options.js](https://github.com/bokub/lyo/blob/master/lib/options.js), and add a value to `flags` if that's true (name it `babelConfig` or something like that).

Then, in [task.js](https://github.com/bokub/lyo/blob/master/lib/task.js), you will find your value in `opts`
